version: "3"

volumes:
  pgdata:
    driver: local
  dbdump:
    driver: local
  solrdata:
    driver: local
  rabbitdata:
    driver: local
  redisdata:
    driver: local

networks:
  lidarrmetadata:

services:
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped

    volumes:
      - redisdata:/data
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    networks:
      - lidarrmetadata
      
  db:
    image: ta264/musicbrainz-postgres
    restart: unless-stopped
    
    volumes:
      - pgdata:/var/lib/postgresql/data

    env_file:
      - ./postgres.env
    
    networks:
      - lidarrmetadata

  musicbrainz:
    image: ta264/musicbrainz-server
    restart: unless-stopped

    volumes:
      - dbdump:/media/dbdump

    env_file:
      - ./postgres.env

    depends_on:
      - db
      - redis

    networks:
      - lidarrmetadata

  solr:
    image: ta264/musicbrainz-solr
    restart: unless-stopped
  
    volumes:
      - solrdata:/opt/solr/server/solr/data
    
    networks:
      - lidarrmetadata

  sir:
    build:
        context: sir
    restart: unless-stopped

    depends_on:
      - db
      - rabbit
      - solr
    
    networks:
      - lidarrmetadata

  rabbit:
    image: rabbitmq:3.6
    restart: unless-stopped

    volumes:
      - rabbitdata:/var/lib/rabbitmq/mnesia
    
    hostname: rabbit
  
    environment:
      RABBITMQ_DEFAULT_USER: "abc"
      RABBITMQ_DEFAULT_PASS: "abc"
    
    networks:
      - lidarrmetadata

