version: '3'
services:
  metadata:
    build: .

    depends_on:
      - redis
      - musicbrainz

    networks:
      - lidarrmetadata

    ports:
      - 5001:5001

    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf

    networks:
      - lidarrmetadata

    volumes:
      - /opt/redis:/data
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5

  musicbrainz:
    image: linuxserver/musicbrainz

    networks:
      - lidarrmetadata

    environment:
      - BRAINZCODE=
      - NPROC=3
      - PUID=
      - PGID=

    volumes:
      - /opt/musicbrainz/config:/config
      - /opt/musicbrainz/data:/data

    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5

networks:
  lidarrmetadata:
